"""
XLSXExportBuilder — pure XLSX generation using openpyxl.

Generates a multi-sheet workbook:
  Sheet 1: Summary   — run stats, match rate
  Sheet 2: Matches   — all MatchCandidates (confidence, strategy, deltas)
  Sheet 3: Exceptions — all ExceptionItems (reason, AI explanation)

No DB access. Takes plain dicts. Returns bytes.
"""
import io
from datetime import datetime
from decimal import Decimal
from typing import Any

import openpyxl
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

# ── Colour palette ─────────────────────────────────────────────────────────────
HEADER_FILL = PatternFill(start_color="1E293B", end_color="1E293B", fill_type="solid")
HEADER_FONT = Font(color="FFFFFF", bold=True, size=10)

MATCHED_FILL = PatternFill(start_color="D1FAE5", end_color="D1FAE5", fill_type="solid")  # green-50
PENDING_FILL = PatternFill(start_color="FEF3C7", end_color="FEF3C7", fill_type="solid")  # amber-50
EXCEPTION_FILL = PatternFill(start_color="FEE2E2", end_color="FEE2E2", fill_type="solid")  # red-50

SUMMARY_LABEL_FONT = Font(bold=True, size=10)
TITLE_FONT = Font(bold=True, size=14, color="1E293B")


def build_xlsx(
    run_name: str,
    run_status: str,
    run_date: str,
    match_rate_pct: int | None,
    total_source_rows: int,
    total_target_rows: int,
    matched_count: int,
    exception_count: int,
    matches: list[dict[str, Any]],
    exceptions: list[dict[str, Any]],
) -> bytes:
    """Build and return a complete XLSX workbook as bytes."""
    wb = openpyxl.Workbook()

    _build_summary_sheet(
        wb,
        run_name=run_name,
        run_status=run_status,
        run_date=run_date,
        match_rate_pct=match_rate_pct,
        total_source_rows=total_source_rows,
        total_target_rows=total_target_rows,
        matched_count=matched_count,
        exception_count=exception_count,
    )
    _build_matches_sheet(wb, matches)
    _build_exceptions_sheet(wb, exceptions)

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf.read()


# ── Sheet builders ─────────────────────────────────────────────────────────────

def _build_summary_sheet(
    wb: openpyxl.Workbook,
    run_name: str,
    run_status: str,
    run_date: str,
    match_rate_pct: int | None,
    total_source_rows: int,
    total_target_rows: int,
    matched_count: int,
    exception_count: int,
) -> None:
    ws = wb.active
    ws.title = "Summary"
    ws.column_dimensions["A"].width = 30
    ws.column_dimensions["B"].width = 30

    # Title
    ws["A1"] = "Reconciliation Report"
    ws["A1"].font = TITLE_FONT
    ws.merge_cells("A1:B1")

    rows = [
        ("Run Name", run_name),
        ("Status", run_status),
        ("Run Date", run_date),
        ("", ""),
        ("Source Records", total_source_rows),
        ("Target Records", total_target_rows),
        ("Matched Rows", matched_count),
        ("Unmatched / Exceptions", exception_count),
        ("Match Rate", f"{match_rate_pct}%" if match_rate_pct is not None else "N/A"),
    ]
    for i, (label, value) in enumerate(rows, start=3):
        ws.cell(row=i, column=1, value=label).font = SUMMARY_LABEL_FONT
        ws.cell(row=i, column=2, value=str(value) if value != "" else "")

    # Match rate cell color
    rate_row = 11
    rate_cell = ws.cell(row=rate_row, column=2)
    if match_rate_pct is not None:
        if match_rate_pct >= 90:
            rate_cell.fill = MATCHED_FILL
        elif match_rate_pct >= 70:
            rate_cell.fill = PENDING_FILL
        else:
            rate_cell.fill = EXCEPTION_FILL

    # Footer
    ws.cell(row=14, column=1, value="Generated by Recon Worker")
    ws.cell(row=14, column=1).font = Font(italic=True, size=9, color="94A3B8")


def _build_matches_sheet(wb: openpyxl.Workbook, matches: list[dict[str, Any]]) -> None:
    ws = wb.create_sheet("Matches")

    headers = [
        "Match ID", "Strategy", "Confidence", "Status",
        "Source Record ID", "Source Table",
        "Target Record ID", "Target Table",
        "Amount Delta", "Date Delta (Days)",
        "Review Note",
    ]
    _write_header_row(ws, headers)

    col_widths = [36, 16, 12, 18, 36, 20, 36, 20, 16, 18, 40]
    for i, w in enumerate(col_widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w

    for i, m in enumerate(matches, start=2):
        strategy = m.get("match_strategy", "")
        status = m.get("status", "")
        confidence = m.get("confidence_score", 0)

        row = [
            str(m.get("id", "")),
            strategy,
            confidence,
            status,
            str(m.get("source_record_id", "")),
            m.get("source_table", ""),
            str(m.get("target_record_id", "")),
            m.get("target_table", ""),
            _fmt_decimal(m.get("amount_delta")),
            m.get("date_delta_days", ""),
            m.get("review_note", "") or "",
        ]
        for j, val in enumerate(row, 1):
            cell = ws.cell(row=i, column=j, value=val)

        # Row colour by status
        fill = MATCHED_FILL if status in ("MATCHED", "APPROVED") else PENDING_FILL
        for j in range(1, len(headers) + 1):
            ws.cell(row=i, column=j).fill = fill


def _build_exceptions_sheet(wb: openpyxl.Workbook, exceptions: list[dict[str, Any]]) -> None:
    ws = wb.create_sheet("Exceptions")

    headers = [
        "Exception ID", "File Role", "Reason", "Status",
        "Amount", "Currency",
        "Record ID", "Record Table",
        "AI Explanation",
        "Resolution Note",
    ]
    _write_header_row(ws, headers)

    col_widths = [36, 12, 22, 16, 14, 10, 36, 20, 80, 40]
    for i, w in enumerate(col_widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w

    for i, e in enumerate(exceptions, start=2):
        status = e.get("status", "")
        row = [
            str(e.get("id", "")),
            e.get("file_role", ""),
            e.get("reason", ""),
            status,
            _fmt_decimal(e.get("amount")),
            e.get("currency", "INR"),
            str(e.get("record_id", "")),
            e.get("record_table", ""),
            e.get("ai_explanation", "") or "",
            e.get("resolution_note", "") or "",
        ]
        for j, val in enumerate(row, 1):
            cell = ws.cell(row=i, column=j, value=val)
            if j == 9:  # AI explanation — wrap text
                cell.alignment = Alignment(wrap_text=True, vertical="top")

        fill = MATCHED_FILL if status in ("RESOLVED", "WAIVED") else EXCEPTION_FILL
        for j in range(1, len(headers) + 1):
            ws.cell(row=i, column=j).fill = fill


# ── Helpers ────────────────────────────────────────────────────────────────────

def _write_header_row(ws, headers: list[str]) -> None:
    for j, h in enumerate(headers, 1):
        cell = ws.cell(row=1, column=j, value=h)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[1].height = 20


def _fmt_decimal(value: Any) -> str | float:
    if value is None:
        return ""
    try:
        return float(Decimal(str(value)))
    except Exception:
        return str(value)
