"""
Audit event type enums.
"""
from enum import Enum


class AuditEventType(str, Enum):
    USER_SIGNED_IN = "USER_SIGNED_IN"
    WORKSPACE_CREATED = "WORKSPACE_CREATED"
    FILE_UPLOADED = "FILE_UPLOADED"
    FILE_PARSED = "FILE_PARSED"
    COLUMN_MAPPING_SUGGESTED = "COLUMN_MAPPING_SUGGESTED"
    COLUMN_MAPPING_CONFIRMED = "COLUMN_MAPPING_CONFIRMED"
    NORMALIZATION_COMPLETED = "NORMALIZATION_COMPLETED"
    RECONCILIATION_STARTED = "RECONCILIATION_STARTED"
    RECONCILIATION_COMPLETED = "RECONCILIATION_COMPLETED"
    MATCH_APPROVED = "MATCH_APPROVED"
    MATCH_REJECTED = "MATCH_REJECTED"
    EXCEPTION_RESOLVED = "EXCEPTION_RESOLVED"
    REPORT_EXPORTED = "REPORT_EXPORTED"
