"""
Exception-related enums for reconciliation.
"""
from enum import Enum


class ExceptionType(str, Enum):
    MISSING_INVOICE = "MISSING_INVOICE"
    MISSING_PAYMENT = "MISSING_PAYMENT"
    MISSING_SETTLEMENT = "MISSING_SETTLEMENT"
    MISSING_BANK_CREDIT = "MISSING_BANK_CREDIT"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    FEE_MISMATCH = "FEE_MISMATCH"
    TAX_MISMATCH = "TAX_MISMATCH"
    REFUND_MISMATCH = "REFUND_MISMATCH"
    DUPLICATE_PAYMENT = "DUPLICATE_PAYMENT"
    DELAYED_SETTLEMENT = "DELAYED_SETTLEMENT"
    UNKNOWN_BANK_CREDIT = "UNKNOWN_BANK_CREDIT"
    OFFLINE_PAYMENT_CANDIDATE = "OFFLINE_PAYMENT_CANDIDATE"
    CHARGEBACK_OR_DISPUTE = "CHARGEBACK_OR_DISPUTE"
    CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
    NET_SETTLEMENT_DIFF = "NET_SETTLEMENT_DIFF"
    NEEDS_MANUAL_REVIEW = "NEEDS_MANUAL_REVIEW"
    UNSETTLED_PAYMENT = "UNSETTLED_PAYMENT"
    UNKNOWN_SETTLEMENT = "UNKNOWN_SETTLEMENT"
    SETTLEMENT_BATCH_AMOUNT_DIFF = "SETTLEMENT_BATCH_AMOUNT_DIFF"


class ExceptionSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ExceptionStatus(str, Enum):
    OPEN = "OPEN"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    RESOLVED = "RESOLVED"
    IGNORED = "IGNORED"


class ExceptionStatusV1(str, Enum):
    """Old status enum for transition/compat."""
    OPEN = "OPEN"
    UNDER_REVIEW = "UNDER_REVIEW"
    RESOLVED = "RESOLVED"
    WAIVED = "WAIVED"
