"""
File ingestion enums.
"""
from enum import Enum


class FileCategory(str, Enum):
    STRIPE_REPORT = "STRIPE_REPORT"
    RAZORPAY_REPORT = "RAZORPAY_REPORT"
    CHARGEBEE_INVOICE_EXPORT = "CHARGEBEE_INVOICE_EXPORT"
    CHARGEBEE_TRANSACTION_EXPORT = "CHARGEBEE_TRANSACTION_EXPORT"
    BANK_STATEMENT = "BANK_STATEMENT"
    INVOICE_EXPORT = "INVOICE_EXPORT"
    RAZORPAY_SETTLEMENT = "RAZORPAY_SETTLEMENT"
    STRIPE_PAYOUT = "STRIPE_PAYOUT"


class UploadedFileStatus(str, Enum):
    UPLOADED = "UPLOADED"
    PARSING = "PARSING"
    PARSED = "PARSED"
    PARSE_FAILED = "PARSE_FAILED"
    NORMALIZING = "NORMALIZING"
    NORMALIZED = "NORMALIZED"
    NORMALIZE_FAILED = "NORMALIZE_FAILED"
    ARCHIVED = "ARCHIVED"


class SourceRecordStatus(str, Enum):
    PARSED = "PARSED"
    INVALID = "INVALID"
