"""
File ingestion enums.
"""
from enum import StrEnum


class FileCategory(StrEnum):
    STRIPE_REPORT = "STRIPE_REPORT"
    RAZORPAY_REPORT = "RAZORPAY_REPORT"
    CHARGEBEE_INVOICE_EXPORT = "CHARGEBEE_INVOICE_EXPORT"
    CHARGEBEE_TRANSACTION_EXPORT = "CHARGEBEE_TRANSACTION_EXPORT"
    BANK_STATEMENT = "BANK_STATEMENT"
    INVOICE_EXPORT = "INVOICE_EXPORT"


class UploadedFileStatus(StrEnum):
    UPLOADED = "UPLOADED"
    PARSING = "PARSING"
    PARSED = "PARSED"
    PARSE_FAILED = "PARSE_FAILED"
    NORMALIZING = "NORMALIZING"
    NORMALIZED = "NORMALIZED"
    NORMALIZE_FAILED = "NORMALIZE_FAILED"
    ARCHIVED = "ARCHIVED"


class SourceRecordStatus(StrEnum):
    PARSED = "PARSED"
    INVALID = "INVALID"
